export enum WsEvent {
    RT_MESSAGES_IN_CONVERSATION = "RT_MESSAGES_IN_CONVERSATION",
    NEW_CONVERSATION_MSG__INFO = "NEW_CONVERSATION_MSG__INFO",
    INVALID_EVENT = "INVALID_EVENT",
    NONE = "NONE"
}

