class WsMessageType {
    static REQUEST_TOKEN_MSG_TYPE = "REQUEST_TOKEN_MSG";
    static RETURN_TOKEN_MSG_TYPE = "RETURN_TOKEN_MSG";

    static ACCESS_GRANTED_MSG_INFO_TYPE = "ACCESS_GRANTED_MSG_INFO_TYPE";
    static ACCESS_DENIED_MSG_INFO_TYPE = "ACCESS_DENIED_MSG_INFO_TYPE";
}

export default WsMessageType;